# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 22:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('introduction', models.TextField(max_length=250)),
                ('body', models.TextField()),
                ('media_url', models.URLField(blank=True, null=True)),
                ('published_date', models.DateTimeField(default=datetime.datetime(2017, 5, 8, 22, 34, 31, 992634, tzinfo=utc))),
            ],
        ),
        migrations.RenameField(
            model_name='blogs',
            old_name='owner',
            new_name='blogger',
        ),
        migrations.AddField(
            model_name='post',
            name='blogs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='blogs.Blog'),
        ),
    ]
